eclipse-edc/RegistrationService

.github/actions/gradle-setup/action.yml
extensions/registration-service/src/main/java/org/eclipse/dataspaceconnector/registration/manager/ParticipantManager.java

Use latest EDC version to bring latest changes.
Due to an EDC class rename, registration service was incompatible to run with latest version of EDC.
Related to https://github.com/agera-edc/MinimumViableDataspace/issues/56

Upgrade to latest EDC version

---

build.gradle.kts
gradle.properties

This PR adds configuration properties and plugins necessary for publishing artifacts to MavenCentral and OSSRH Staging (when the `-SNAPSHOT` suffix is added to the version.
When building connector images in MVD we need to pull in Maven dependencies from EDC core (already exists), and the RegistrationService.
- the `projectVersion` property was refactored to `defaultVersion` because it should/must be necessary to override the version with a flag: `-PregSrvVersion=....`
- I chose to call the version override flag `regSrvVersion` because a `version` property already exists with a default value of `unspecified`, and as far as I know kotlin ternary operators only exist for nullable expressions, not for boolean ones.
- The Jenkins job is set up to poll the `main` branch every 30 minutes for …

feat(build): add signing config

---

docs/developer/decision-records/2022-06-13-registration-service-api/README.md

This PR adds retroactively decision record documentation about Registration Service API.  
To keep track of the development decisions.
More abstract documentation containing high level flows will be added to MVD repo.
Closes https://github.com/agera-edc/MinimumViableDataspace/issues/20

Feature/20 Registration Service API ADR

---

.github/workflows/verify.yaml
build.gradle.kts

- Use jacoco plugin for test coverage.
- Upload test coverage data to CodeCov.
- Restrict push trigger to main branch only. To avoid duplicate workflow runs on PRs
Codecov report https://codecov.io/github/agera-edc/RegistrationService/commit/863403fc5f6c30cb771ff1c5530ca9767b1e8ede
These are implemented exactly like in EDC and MVD (https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/pull/52)
Improved reporting, aligned with EDC practices.
Relates to https://github.com/agera-edc/MinimumViableDataspace/issues/251

Test reports and code coverage

---

.github/workflows/codeql-analysis.yml
.github/workflows/verify.yaml
build.gradle.kts
docs/developer/2022-08-15-code-quality-tooling/README.md
resources/checkstyle-config.xml

Added checkstyle and codeql in workflows.
Example of failing workflow: https://github.com/agera-edc/RegistrationService/runs/7840323571?check_suite_focus=true
To detect checkstyle errors + have codeql running when creating PRs.
Same PR as in IdentityHub, the difference is that the path to the suppress file is setup in order to ignore generated resources.
https://github.com/agera-edc/MinimumViableDataspace/issues/253

Added checkstyle and codeql.

---

rest-client/build.gradle.kts
rest-client/src/main/java/org/eclipse/dataspaceconnector/registration/client/ApiClientFactory.java

Configure connect and read timeout for rest client. readTimeout is 60 seconds and connectTimeout is 30 seconds.
It was observed that client calls didn't timeout which mean CI steps can be running until it reaches CI timeout limit. Which can be very high e.g. 1 hour. For example, see CI run here https://github.com/agera-edc/MinimumViableDataspace/runs/7874926981?check_suite_focus=true  which kept on running until cancelled manually.
Relates to https://github.com/agera-edc/MinimumViableDataspace/issues/46

Configure connect and read timeout for rest client

---

extensions/dataspace-authority-spi/src/main/java/org/eclipse/dataspaceconnector/registration/authority/model/Participant.java
extensions/registration-service/build.gradle.kts
extensions/registration-service/src/main/java/org/eclipse/dataspaceconnector/registration/AuthorityExtension.java
extensions/registration-service/src/main/java/org/eclipse/dataspaceconnector/registration/api/RegistrationService.java
extensions/registration-service/src/main/java/org/eclipse/dataspaceconnector/registration/manager/ParticipantManager.java
extensions/registration-service/src/test/java/org/eclipse/dataspaceconnector/registration/api/RegistrationServiceTest.java
extensions/registration-service/src/test/java/org/eclipse/dataspaceconnector/registration/manager/ParticipantManagerTest.java
gradle.properties
launcher/Dockerfile
launcher/build.gradle.kts
launcher/logging.properties

This PR enables tracing observability data: logs, metrics, traces. It adds the application insights java agent to the Dockerfile.
Logs:
- Add JDK Monitor Logger extension
- Add logging configuration file
Metrics:
- Add extension for enabling jetty, jersey and default metrics 
Traces:
- Trace context propagation for state machine operations
- Add @WithSpan annotation to methods where the Participant changes the onboarding status.
Traces in Application Insights from local Registration Service set up:
We want to be able to monitor the application.
In the future we can clean up the Dockerfile and remove the application insights java agent jar from there. Instead we can create custom launcher for Registration Service in MVD to extend the Dockerfile adding the app insights java agent jar. …

Collect observability data

---

extensions/dataspace-authority-spi/build.gradle.kts
extensions/participant-store-spi/build.gradle.kts
extensions/participant-verifier/build.gradle.kts
extensions/registration-policy-gaiax-member/build.gradle.kts
extensions/registration-service/build.gradle.kts

Add missing `publishing` task for all extensions.
Each extension must publish an artifact.

fix: Add missing `publishing` task for all extensions

---

.github/workflows/release-registrationservice.yml

Adds a workflow for releasing artefacts to OSSRH Staging and MavenCentral right from within Github.
Convenient version creation.
verified correct function in my [fork](https://github.com/paullatzelsperger/RegistrationService/actions/runs/3053485127/jobs/4924165675)

build: add release workflow

---

extensions/store/sql/participant-store-sql/src/main/java/org/eclipse/dataspaceconnector/registration/store/sql/SqlParticipantStore.java
extensions/store/sql/participant-store-sql/src/test/java/org/eclips/dataspaceconnector/registration/store/sql/PostgresParticipantStoreTest.java
gradle.properties

Make the `SqlParticipantStore` extends `AbstractSqlStore` and make usage of the `PostgresqlStoreSetupExtension` for 
the test setup
Reduce duplicated code when in the SQL store implementation and testing.
Closes #49

refactor(SqlParticipantStore): apply AbstractSqlStore class and PostgresqlStoreSetupExtension in test

---

client-cli/build.gradle.kts
client-cli/src/main/java/org/eclipse/edc/registration/cli/RegistrationServiceCli.java

Replaces the use of an `OkHttpClient` with the newly introduced `EdcHttpClient`.
Upstream changes, broke the build.
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

chore: fix compile error due to upstream changes

---

client-cli/src/main/java/org/eclipse/edc/registration/cli/RegistrationServiceCli.java

adds the `-u <REG_SRV_URL>` flag to the CLI to override the registration service URL.
This feature is useful in docker environments, where the RegistrationService is known under its Docker network hostname (`"registration-service"`) but the CLI is used from outside docker.
.

feat: add override flag for RegSrv URL

---

client-cli/src/main/java/org/eclipse/edc/registration/cli/RegistrationServiceCli.java

Adds the `Monitor` argument to the `EdcHttpClient`'s constructor args when creating the RegistrationService CLI
compile errors
.
.

fix: add Monitor to EdcHttpClient's arguments

---

core/registration-service-credential-service/src/main/java/org/eclipse/edc/registration/VerifiableCredentialServiceExtension.java
core/registration-service-credential-service/src/main/java/org/eclipse/edc/registration/credential/DefaultOnboardedParticipantCredentialProvider.java
core/registration-service-credential-service/src/main/java/org/eclipse/edc/registration/service/VerifiableCredentialServiceImpl.java
core/registration-service-credential-service/src/test/java/org/eclipse/edc/registration/credential/DefaultOnboardedParticipantCredentialProviderTest.java
core/registration-service-credential-service/src/test/java/org/eclipse/edc/registration/service/VerifiableCredentialServiceImplTest.java
system-tests/src/test/java/org/eclipse/edc/registration/client/RegistrationApiClientTest.java
system-tests/src/test/java/org/eclipse/edc/registration/client/RegistrationApiCommandLineClientTest.java

Use `EdcHttpClient` instead of `OkHttpClient`.
`EdcHttpClient` embeds failsafe.
Closes #65

refactor: Use EdcHttpClient

---

core/registration-service-client/build.gradle.kts
core/registration-service-onboarding-policy-verifier/build.gradle.kts
extensions/store/sql/participant-store-sql/build.gradle.kts
launcher/build.gradle.kts
registration-service-cli/build.gradle.kts
spi/registration-service-spi/build.gradle.kts
spi/registration-service-store-spi/build.gradle.kts
system-tests/build.gradle.kts
system-tests/launchers/participant/build.gradle.kts

Removes the Maven publications from the build files and sets the `publish` flag to false for modules that should not be published (launchers, system tests).
Once [this PR](https://github.com/eclipse-edc/GradlePlugins/pull/67) is merged, Maven publications will be added automatically by the Plugin.

chore: remove publications

---

extensions/store/cosmos/participant-store-cosmos/src/main/java/org/eclipse/edc/registration/store/cosmos/CosmosParticipantStore.java

Fix the compilation issue in `CosmosParticipantStore`
It does not compile
Closes #78  
Checklist

fix(CosmosParticipantStore): adds upsert manual semantic

---

.github/workflows/verify.yaml
build.gradle.kts
core/registration-service-client/build.gradle.kts
core/registration-service-client/src/main/java/org/eclipse/edc/registration/client/ApiClientFactory.java
core/registration-service-client/src/main/java/org/eclipse/edc/registration/client/JsonWebSignatureHeaderInterceptor.java
core/registration-service-client/src/main/java/org/eclipse/edc/registration/client/RegistryApiClient.java
core/registration-service-client/src/main/java/org/eclipse/edc/registration/client/RegistryApiClientFactory.java
core/registration-service-client/src/main/java/org/eclipse/edc/registration/client/RegistryApiClientImpl.java
core/registration-service-client/src/main/java/org/eclipse/edc/registration/client/model/ParticipantDto.java
core/registration-service-client/src/main/java/org/eclipse/edc/registration/client/response/ApiFailure.java
core/registration-service-client/src/main/java/org/eclipse/edc/registration/client/response/ApiResult.java
core/registration-service-client/src/test/java/org/eclipse/edc/registration/client/RegistryApiClientImplTest.java
core/registration-service/src/main/java/org/eclipse/edc/registration/store/InMemoryParticipantStore.java
extensions/store/cosmos/participant-store-cosmos/src/main/java/org/eclipse/edc/registration/store/cosmos/CosmosParticipantStore.java
extensions/store/sql/participant-store-sql/src/main/java/org/eclipse/edc/registration/store/sql/SqlParticipantStore.java
registration-service-cli/src/main/java/org/eclipse/edc/registration/cli/ClientUtils.java
registration-service-cli/src/main/java/org/eclipse/edc/registration/cli/GetParticipantCommand.java
registration-service-cli/src/main/java/org/eclipse/edc/registration/cli/ListParticipantsCommand.java
registration-service-cli/src/main/java/org/eclipse/edc/registration/cli/RegistrationServiceCli.java
registration-service-cli/src/test/java/org/eclipse/edc/registration/cli/ClientUtilsTest.java
registration-service-cli/src/test/java/org/eclipse/edc/registration/cli/ParticipantsCommandTest.java
registration-service-cli/src/test/java/org/eclipse/edc/registration/cli/TestUtils.java
settings.gradle.kts
spi/registration-service-store-spi/src/main/java/org/eclipse/edc/registration/store/spi/ParticipantStore.java
system-tests/src/test/java/org/eclipse/edc/registration/client/RegistrationApiClientTest.java
system-tests/src/test/java/org/eclipse/edc/registration/client/RegistrationApiCommandLineClientTest.java
system-tests/src/test/java/org/eclipse/edc/registration/client/RegistrationServiceTestUtils.java

Replaces the auto-generated API client with an "explicitly" implemented one.
both the API controller and the client are in this repository, so it does not make much sense to generate the client.
Further, the generated one used the Java Http client, whereas now we can use the `EdcHttpClient`.
- added a smoke test against a `MockWebServer` to verify that the client sends the correct requests.
Closes #75

refactor: replace generated ApiClient with a manual one

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/verify.yaml
docs/developer/decision-records/2022-06-29-http-ports/README.md
gradle/libs.versions.toml
launcher/build.gradle.kts
system-tests/README.md

Remove control-plane dependency from the `launcher`
A registration service shouldn't declare the `control-plane` dependencies.
- updated docker-compose
- sync'd pull request template
Closes #88

fix(build): remove unused launcher dependency

---

.github/actions/bump-version/action.yml
.github/workflows/release-registrationservice.yml

Adds a job to automatically bump the version after a GH release
updated the version automatically
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

build: add action to bump the snapshot version

---

.github/actions/bump-version/action.yml
core/registration-service-credential-service/src/main/java/org/eclipse/edc/registration/VerifiableCredentialServiceExtension.java
extensions/store/cosmos/participant-store-cosmos/src/main/java/org/eclipse/edc/registration/store/cosmos/CosmosParticipantStoreExtension.java
extensions/store/sql/participant-store-sql/src/main/java/org/eclipse/edc/registration/store/sql/SqlParticipantStoreExtension.java
gradle.properties
gradle/libs.versions.toml

Update snapshot version to `0.1.0-SNAPSHOT`
Our next release version will be `0.1.0`, thus the next snapshot will be `0.1.1-SNAPSHOT` and the automatic version bump mechanism currently only bumps the `patch` version.
- depends on https://github.com/eclipse-edc/GradlePlugins/pull/162
- depends on https://github.com/eclipse-edc/Connector/pull/3108
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md)._

chore: update snapshot version to 0.1.0-SNAPSHOT

---

DEPENDENCIES
gradle/libs.versions.toml

Pins the version of all IdenityHub modules to 0.3.1, which is the last release that contains the DWN variant of IH.
Compile errors. 
- RegistrationService will have to undergo a serious re-engineering once the IH tasks are complete.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

chore: pin IdentityHub version

---

DEPENDENCIES
gradle/libs.versions.toml
spi/registration-service-spi/build.gradle.kts

removes aggregate-service-spi dependency, that was inlined in https://github.com/eclipse-edc/Connector/pull/3578
fix release, it gave error like this: https://github.com/eclipse-edc/Release/actions/runs/6844409607/job/18618464261
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

build: remove unexistent dependency
